### ISSUE TITLE
配额不足，无法处理此命令

### ISSUE THREAD

**Issue by chenxuuu** [chenxuuu/llcom#26]
一直有这个bug的上报，先记一下，目前原因不明

## System.ComponentModel.Win32Exception: 配额不足，无法处理此命令。

at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
at  System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd,  Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at  System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,  Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Application | llcom
-- | --
Version | 1.0.5.8
Date | 2021-04-29 00:44:06Z
OS | Windows 10
CLR | 4.0.30319.42000
CrashReporter.NET Version | 1.6.0.0

## User Description

模块断开USB连接后，程序崩溃

**Comment by chenxuuu** [comment]
更改为x64后似乎没遇到过了
